config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'pages#home'
  get 'about', to: 'pages#about'
  get 'guide', to: 'pages#guide'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :offers do
    resources :bookings, only: [:create, :new, :edit, :update, :destroy]
    resources :reviews, only: :create
  end
  resources :bookings, only: [:show, :edit, :update, :destroy, :index] do
  end

  get 'my_offers', to: 'offers#my_offers', as: :my_offers
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :offer
  belongs_to :user

  has_many :reviews, dependent: :destroy
end

app/models/offer.rb
class Offer < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reviews, through: :bookings
  belongs_to :user

  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  has_one_attached :photo

  validates :price, presence: true
  validates :title, presence: true
  validates :description, presence: true
  validates :duration, presence: true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :offer
  validates :content, length: { minimum: 5 }, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 10 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  #validates :name, :email, :password
  has_many :bookings
  has_many :offers
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # def after_sign_in_path_for(resource)
  #   offers_path
  # end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
    @booking = Booking.new
    @offer = Offer.find(params[:offer_id])
  end

  def index
    @bookings = Booking.all
  end

  def create
    #@reviews = Review.new
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.offer = Offer.find(params[:offer_id])
    if @booking.save
      flash[:notice] = "Booking successfully done"
      redirect_to offers_path(@offers)
    else
      flash[:error] = "Something went wrong"
      render :new
    end
  end

  def my_bookings
    @bookings = current_user.bookings
  end

  def edit
    @booking = Booking.find(params[:id])
  end

  def update
    @booking = Booking.find(params[:id])
    if @booking.update(booking_params)
      flash[:notice] = "Booking successfully changed"
      redirect_to bookings_path
    else
      render :edit
    end
  end

  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    redirect_to my_bookings_path(@offers)
  end

  private

  def booking_params
    params.require(:booking).permit(:starting_date, :ending_date)
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    @offers = Offer.all

    @markers = @offers.geocoded.map do |offer|
      {
        lat: offer.latitude,
        lng: offer.longitude,
        info_window: render_to_string(partial: "info_window", locals: { offer: offer })
      }
    end
  end

  def show
    @offer = Offer.find(params[:id])
    @review = Review.new

    @markers = [
      {
        lat: @offer.latitude,
        lng: @offer.longitude,
        info_window: render_to_string(partial: "info_window", locals: { offer: @offer }),
        image_url: helpers.asset_url("/assets/images/marker.png")
      }
    ]
  end

  def new
    @offer = Offer.new
  end

  def create
    @offer = Offer.new(offer_params)
    @offer.user = current_user
    if @offer.save
      redirect_to offer_path(@offer)
    else
      render :new
    end
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    @offer = Offer.find(params[:id])
    if @offer.update(offer_params)
      redirect_to my_offers_path
    else
      render :edit
    end
  end

  def my_offers
    @offers = current_user.offers
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy

    redirect_to my_offers_path(@offers)
  end

  private

  def offer_params
    params.require(:offer).permit(:photo, :title, :description, :price, :duration, :location)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def create
    @offer = Offer.find(params[:offer_id])
    @review = Review.new(review_params)
    @review.booking = @offer.bookings.first
    if @review.save
      flash[:success] = 'Review created!'
      redirect_to offer_path(@offer)
    else
      flash[:error] = "Review wasn't saved"
      render 'offers/show'
    end
  end

  private

  def review_params
    params.require(:review).permit(:rating, :content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bookings/edit.html.erb
<div class="mt-5 mx-5">
<h1 class="text-center">Edit your booking</h1>
<ul>
<%= simple_form_for @booking do |f| %>
  <%= f.input :starting_date %>
  <%= f.input :ending_date %>
  <%= f.submit :submit, class: "btn btn-primary" %>
<% end %>
<div class="pt-5 center"><%= link_to 'Back to bookings page', root_path, class: "btn btn-accent" %></div>
</div>

app/views/bookings/index.html.erb
<div class="mt-5 mx-5">
<h1 class="text-center">Bookings Overview</h1>
<div class="mt-5 mx-5">
<table class="table shadow p-5 bg-white rounded">
  <thead>
    <tr>
      <th scope="col">Title</th>
      <th scope="col">Starting Date</th>
      <th scope="col">End Date</th>
      <th scope="col">Booking created</th>
      <th scope="col">Actions</th>
      <th scope="col"></th>
    </tr>
  </thead>
  <tbody>
  <% @bookings.each do |booking| %>
    <tr>
      <th scope="row"><%= booking.offer.title%></th>
      <td><%= booking.starting_date %></td>
      <td><%= booking.ending_date %></td>
      <td><%= booking.created_at.day%>-<%= booking.created_at.month%>-<%= booking.created_at.year %></td>
      <td><%= link_to 'Edit', edit_booking_path(booking.id), class: "btn btn-accent" %></td>
      <td><%= link_to 'Delete', "#" %></td>
    </tr>
      <% end %>
  </tbody>
</table>
</div>

</div>

app/views/bookings/my_bookings.html.erb
  <div class="container">
    <h1>My bookings</h1>
  </div>
<div class="mt-5 mx-5 cards content">
<% @bookings.each do |booking| %>
  <div class="card-category">
    <%= booking.offer.title %>
    <%= link_to 'My bookings', booking_path(booking) %>
  </div>
<% end %>
</div>

app/views/bookings/new.html.erb
<div class="mt-5 mx-5">
  <h1 class="text-center">Here is your offers</h1>
  <div class="form">
    <%= simple_form_for [@offer, @booking] do |f| %>
      <%= f.input :starting_date %>
      <%= f.input :ending_date %>
      <%= f.submit "Submit Booking", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LearningHub</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
  </head>

  <body>

  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <div class="body">
    <%= yield %>
  </div>
  <%= render 'shared/footer' %>


  </body>
</html>

app/views/offers/_info_window.html.erb
<h2><%= offer.title %></h2>
<p><%= offer.location %></p>

app/views/offers/edit.html.erb
<div class="mt-5 mx-5" id="form">
<h1 class="text-center">Edit or delete your offer</h1>
<ul>
<br>
<%= simple_form_for [ @offer ] do |f| %>
  <%= f.input :photo, as: :file %>
  <%= f.input :price %>
  <%= f.input :duration %>
  <%= f.input :description %>
  <%= f.input :title %>
  <%= f.input :location %>
  <br>
  <br>
  <%= f.submit "Submit", class: "btn btn-primary mt-2" %>
<% end %>
<div class="pt-5 center"><%= link_to 'Back to Homepage', root_path, class: "btn btn-accent ms-0" %></div>
<br>
</div>

app/views/offers/index.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://innovationatwork.ieee.org/wp-content/uploads/2021/01/bigstock-Machine-Learning-Artificial-I-311340295_1024X684.png);">
  <div class="container">
    <h1>Offer Overview</h1>
    <br>
    <p>    Display and edit your offers and let people know what you want to teach.</p>
    <%= link_to 'Create new offer', new_offer_path, class: "btn btn-accent" %>
  </div>
</div>
<div class="mt-5 mx-5 cards content">
<% @offers.each do |offer| %>
  <div class="card-category" style="background-image: url('<%= offer.photo.key.present? ? cl_image_path(offer.photo.key) : '' %>')">
    <%= offer.title %><%= link_to 'Show', offer_path(offer.id) %>
  </div>
<% end %>
</div>
<br>

app/views/offers/my_offers.html.erb
  <div class="container">
    <h1>My offers</h1>
  </div>
<div class="mt-5 mx-5 cards content">
<% @offers.each do |offer| %>
  <div class="card-category" style="background-image: <%= offer.photo %>;">
    <%= offer.title %>
    <%= link_to 'See offer', offer_path(offer)%>
  </div>
<% end %>
</div>

app/views/offers/new.html.erb
<div class="mt-5 mx-5">
<h1 class="text-center">Create a new offer</h1>
<ul>
<%= simple_form_for [ @offer ] do |f| %>
  <%= f.input :photo, as: :file %>
  <%= f.input :price %>
  <%= f.input :duration %>
  <%= f.input :description %>
  <%= f.input :title %>
    <%= f.input :location,
              input_html: { data: { geocoder_target: "location" }, class: "d-none" },
              wrapper_html: { data: { controller: "geocoder", geocoder_api_key_value: ENV['MAPBOX_API_KEY'] } } %>
  <%= f.submit "Submit offer", class: "btn btn-primary" %>
<% end %>
<div class="pt-5 center"><%= link_to 'Back to list page', root_path, class: "btn btn-accent" %></div>
</div>

app/views/offers/show.html.erb
<div class="flex-item">
  <div class="mt-5 mx-5 card-trip">
    <% if @offer.photo.key %>
      <%= cl_image_tag @offer.photo.key, height: 300, width: 400, crop: :fill %>
    <% else %>
      <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
    <% end %>
    <div class="card-trip-infos">
      <div>
        <h1><%= @offer.title %></h1>
        <strong><%= @offer.description %></strong>
      </div>
      <h3><%= @offer.price %> €</h3>
      <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" />
    </div>
    <div class="card-trip-infos d-flex justify-content-start">
      <h5>Duration: <%= @offer.duration %> | </h5>
      <h5> Location: <%= @offer.location %></h5>

      <div id="reviews">
        <% if @offer.reviews.blank? %>
          Be the first to leave a review for <%= @offer.title %>
        <% else %>
          <% @offer.reviews.each do |review| %>
            <p><%= review.content %></p>
          <% end %>
        <% end %>
        <h6>
        <%= pluralize @offer.reviews.size, "review" %>
        </h6>
        <%= simple_form_for([@offer, @review]) do |f| %>
        <%= f.input :comment, as: :text %>
        <%= f.input :rating, as: :float %>
        <%= f.submit 'Create Review', class: "btn btn-accent" %>
        <% end %>
      </div>
    </div>
  </div>
</div>
<div class="mt-5 mx-5">
  <div style="width: 100%; height: 400px;"
    data-controller="mapbox"
    data-mapbox-markers-value="<%= @markers.to_json %>"
    data-mapbox-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
</div>
<div class="mt-5 mb-5 mx-5 footer">
  <%= link_to 'Back', offers_path, class: "btn btn-accent" %>
  <% if     @offer.user == current_user %>
    <%= link_to 'Edit', edit_offer_path, class: "btn btn-accent" %>
    <%= link_to 'Delete', offer_path(@offer), method: :delete,  class: "btn btn-accent" %>
  <% else %>

    <%= link_to 'New booking for this offer', new_offer_booking_path(@offer), class: "btn btn-accent" %>

  <% end %>
</div>
<br>

app/views/pages/about.html.erb
<div class="container mt-5">
  <h1 class="text-center mb-5">About us</h1>
  <div>
     <p class="mb-5" style="font-size: 22px; text-align: center;"> Our main goal is to create a global platform to make learning available to any person around the globe. <br> We try to help people achieve their dreams.</p>
  </div>
  <div class="text-center">
    <img src="https://images.unsplash.com/photo-1548705085-101177834f47?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=3432&q=80" id="group-image" style="width: 50%" >
  </div>
</div>

app/views/pages/guide.html.erb
<div class="mt-5 mx-5">
<h1 class="text-center">Your Guide to learning hub</h1>
  <div class="mt-5 mx-5">
    <div class="accordion" id="accordionExample">
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingOne">
          <button class="accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
            How to use learning-hub
          </button>
        </h2>
        <div id="collapseOne" class="accordion-collapse collapse show" aria-labelledby="headingOne" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <strong>This is the first item's accordion body.</strong> It is shown by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingTwo">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
            What means transparent cost structure
          </button>
        </h2>
        <div id="collapseTwo" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <strong>This is the second item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingThree">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            What to do when login fails?
          </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingThree">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            What to do when login fails?
          </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingThree">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            What to do when login fails?
          </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
          </div>
        </div>
      </div>
      <div class="accordion-item">
        <h2 class="accordion-header" id="headingThree">
          <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
            What to do when login fails?
          </button>
        </h2>
        <div id="collapseThree" class="accordion-collapse collapse" aria-labelledby="headingThree" data-bs-parent="#accordionExample">
          <div class="accordion-body">
            <strong>This is the third item's accordion body.</strong> It is hidden by default, until the collapse plugin adds the appropriate classes that we use to style each element. These classes control the overall appearance, as well as the showing and hiding via CSS transitions. You can modify any of this with custom CSS or overriding our default variables. It's also worth noting that just about any HTML can go within the <code>.accordion-body</code>, though the transition does limit overflow.
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://www.surfingwasurfschool.com.au/wp-content/uploads/2018/05/2021-Jan-SurfingWA-ALL-Edits-7386-scaled.jpg);">
  <div class="container">
    <h1><strong>Learning Hub | </strong> Different Stuff to learn with creative people!</h1>
    <br>
    <p> Learn and develop any skill. Connect with our members and start learning today.</p>
    <br>
    <br>
    <a class="btn-accent" href="#">Apply now</a>
  </div>
</div>
<div class="mt-5 mx-5">
    <div class="row mt-5 cards content">
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://upload.wikimedia.org/wikipedia/commons/b/b0/Surf_8508_%2824562138976%29.jpg">
        Surf lesson
      </div>
      <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/lunch.jpg)">
        Vegan Cooking lesson
      </div>
    </div>
      <div class="row mt-5 cards content">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://lh6.googleusercontent.com/RS097RxKppVussyVkm2T_NYwi7WCtw4OX1BluDRhAKZ0ScBpyuuaRczBET03huaEgyJ_mj3ffGOeHVTvwgeZ1NLjpxGIVdx28zJq_qJ-FTGNrpdT_gSp-ksvTrV41p87t27SqMYI=w600)">
          English lesson
        </div>

        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://video-images.vice.com/articles/5a1d844947feed11c542fa6f/lede/1511884559295-DSC07424.jpeg?crop=1xw:0.8411xh;0xw,0.1084xh)">
          Guitar lesson
        </div>
      </div>
      <div class="row mt-5 mb-5 cards content">
        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://www.yogauonline.com/sites/default/files/styles/wellness_blog_level3_main/public/fotolia_46802356_subscription_xl_1.jpg?itok=gKkcd5FR)">
          Yoga lesson
        </div>

        <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://brunswickdowntown.org/wp-content/uploads/2020/06/tennis-lesson.jpg)">
          Tennis lesson
        </div>
      </div>
    </div>
  </div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="#"><i class="fab fa-github"></i></a>
    <a href="#"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-facebook"></i></a>
    <a href="#"><i class="fab fa-twitter"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
  <div class="footer-copyright">
    Learning Hub tries to make <i class="fas fa-heart"></i> with you
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to root_path, class: "navbar-brand" do %>
      <%= image_tag "logo.png", alt: "Learninghub", width: 400 %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "About", "/about", class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Guide", "/guide", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Offers", offers_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle ml-20px", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to 'Create new offer', new_offer_path, class: "dropdown-item" %>
              <%= link_to 'See my offers', my_offers_path, class: "dropdown-item" %>
              <%= link_to "See bookings", bookings_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login / signup", new_user_session_path, class: "btn btn-accent" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/users/signup.html.erb
<%= simple_form_for(@list) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: "btn btn-accent"%>
  </div>
<% end %>

user_signed_in?
# => true / false

current_user
# => User instance / nil